// GENERATED FILE - do not edit by hand. Source: tire_prefixes_FINAL.csv (validated, tiered).
// Regenerate: node scripts/genTirePrefixHints.mjs
// Ingested as prefixes: hint_strong=46, hint_weak=147 (71 distinct prefixes).
// NOT ingested (held out): exclude_partnumber=7, review_before_use=6.
//
// A prefix may map to a brand FAMILY (corporate siblings sharing a GS1 company prefix). A hint may
// only SUGGEST/BOOST a brand - it NEVER marks a scan known/verified, auto-counts, or overrides the
// firewall. A real confirmed scan promotes a brand<-prefix link to trusted via deriveBrandPrefixHints.

export type PrefixWeight = "strong" | "weak";
export interface PrefixHint { brand: string; weight: PrefixWeight; source?: string }

export const TIRE_PREFIX_HINTS: Record<string, PrefixHint[]> = {
  "0191563": [{ brand: "Nexen", weight: "strong" }],
  "025114": [{ brand: "Carlisle", weight: "weak" }, { brand: "ITP", weight: "weak" }, { brand: "Carlisle (Ag)", weight: "weak" }],
  "029142": [{ brand: "Cooper", weight: "strong" }, { brand: "Mastercraft", weight: "strong", source: "https://www.barcodespider.com/029142694212" }, { brand: "Starfire", weight: "strong", source: "https://www.amazon.com/Starfire-Solarus-Season-Radial-Tire-LT215/dp/B07Y7342PX" }, { brand: "Avon Tyres", weight: "weak" }, { brand: "Arizonian", weight: "weak" }, { brand: "Phantom", weight: "weak" }, { brand: "Dean", weight: "weak" }, { brand: "Oliver (Cooper)", weight: "weak" }],
  "040051": [{ brand: "Delta", weight: "weak" }, { brand: "Eldorado", weight: "weak" }, { brand: "Multi-Mile", weight: "weak" }, { brand: "Cordovan", weight: "weak" }, { brand: "Sigma", weight: "weak" }, { brand: "Vanderbilt", weight: "weak" }, { brand: "Power King", weight: "weak" }, { brand: "Towmax", weight: "weak" }, { brand: "Mud Claw", weight: "weak" }, { brand: "Trail Guide", weight: "weak" }, { brand: "Mirada", weight: "weak" }],
  "047853": [{ brand: "Kenda", weight: "strong" }],
  "051342": [{ brand: "General Tire", weight: "strong" }],
  "054137": [{ brand: "Pirelli", weight: "strong" }],
  "0688028": [{ brand: "Hercules", weight: "strong" }, { brand: "Ironman", weight: "strong" }, { brand: "Dynatrac (ATD)", weight: "weak" }],
  "069766": [{ brand: "Dunlop", weight: "strong" }, { brand: "Kelly", weight: "weak" }, { brand: "Debica", weight: "weak" }, { brand: "Sava", weight: "weak" }, { brand: "Fulda", weight: "weak" }, { brand: "Fierce", weight: "weak" }, { brand: "Remington", weight: "weak" }, { brand: "Monarch", weight: "weak" }, { brand: "Lee", weight: "weak" }, { brand: "Republic", weight: "weak" }],
  "0703382": [{ brand: "Nokian", weight: "strong" }],
  "0715459": [{ brand: "Hankook", weight: "strong" }, { brand: "Laufenn", weight: "weak" }, { brand: "Pathfinder", weight: "weak" }],
  "0721506": [{ brand: "Yokohama", weight: "strong" }, { brand: "Alliance", weight: "weak" }, { brand: "Galaxy", weight: "weak" }, { brand: "Galaxy (Ag)", weight: "weak" }, { brand: "Primex (Ag)", weight: "weak" }],
  "0749715": [{ brand: "Crosswind", weight: "strong" }],
  "0758823": [{ brand: "Westlake", weight: "strong" }, { brand: "Milestar", weight: "strong" }, { brand: "Nankang (NA)", weight: "weak" }, { brand: "Freestar", weight: "weak" }, { brand: "Pro-Meter", weight: "weak" }, { brand: "Geostar", weight: "weak" }, { brand: "Geotrac", weight: "weak" }],
  "0768155": [{ brand: "Sumitomo", weight: "strong" }],
  "0787025": [{ brand: "Mickey Thompson", weight: "strong" }, { brand: "Dick Cepek", weight: "weak" }],
  "0818749": [{ brand: "GT Radial", weight: "strong" }, { brand: "Primewell", weight: "weak" }, { brand: "Dextero", weight: "weak" }, { brand: "Dynatrac", weight: "weak" }],
  "0826825": [{ brand: "Toyo Tires (NA)", weight: "weak" }, { brand: "Nitto", weight: "strong" }],
  "0826826": [{ brand: "Sumitomo", weight: "strong" }, { brand: "Doral", weight: "weak" }, { brand: "Solar", weight: "weak" }],
  "08401396": [{ brand: "Fortune", weight: "strong" }, { brand: "Prinx", weight: "weak" }],
  "0840156": [{ brand: "Atturo", weight: "strong" }, { brand: "Lexani", weight: "weak" }, { brand: "Lionhart", weight: "weak" }, { brand: "Arroyo", weight: "weak" }, { brand: "Venom Power", weight: "weak" }, { brand: "Fury", weight: "weak" }, { brand: "Transeagle", weight: "weak" }, { brand: "Gladiator", weight: "weak" }, { brand: "Zenna", weight: "weak" }],
  "0841623": [{ brand: "Sentury", weight: "weak" }, { brand: "Delinte", weight: "strong" }, { brand: "Landsail", weight: "weak" }, { brand: "Groundspeed", weight: "weak" }, { brand: "Pantera", weight: "weak" }, { brand: "American Roadstar", weight: "strong" }],
  "084214": [{ brand: "Coker Tire", weight: "weak" }],
  "0848983": [{ brand: "Falken", weight: "strong" }, { brand: "Ohtsu", weight: "strong", source: "https://www.u-buy.com.ng/product/2MPGKEFI-ohtsu-fp8000-all-season-radial-tire-28525zr20-93w" }, { brand: "Wild Spirit", weight: "weak" }, { brand: "Wild Country", weight: "weak" }],
  "085532": [{ brand: "Vogue", weight: "weak" }],
  "086699": [{ brand: "Michelin", weight: "strong" }, { brand: "BFGoodrich", weight: "strong" }, { brand: "Uniroyal (US)", weight: "strong" }, { brand: "Oliver", weight: "weak" }],
  "088656": [{ brand: "Titan", weight: "weak" }],
  "092971": [{ brand: "Bridgestone", weight: "strong" }, { brand: "Firestone", weight: "strong" }, { brand: "Dayton", weight: "weak" }, { brand: "Fuzion", weight: "strong", source: "https://www.upcindex.com/92971317478" }, { brand: "Bandag", weight: "weak" }],
  "098663": [{ brand: "Kenda", weight: "strong" }],
  "352870": [{ brand: "Michelin", weight: "weak" }, { brand: "Kleber", weight: "weak" }, { brand: "Tigar", weight: "weak" }, { brand: "Riken", weight: "weak" }, { brand: "Kormoran", weight: "weak" }, { brand: "Sebring", weight: "weak" }, { brand: "Siamtyre", weight: "weak" }],
  "4010684": [{ brand: "Falken (EU)", weight: "weak" }],
  "4019238": [{ brand: "Continental", weight: "strong" }, { brand: "Uniroyal (EU)", weight: "weak" }, { brand: "Semperit", weight: "weak" }, { brand: "Barum", weight: "weak" }, { brand: "Viking", weight: "weak" }, { brand: "Gislaved", weight: "weak" }, { brand: "Euzkadi", weight: "weak" }, { brand: "General", weight: "weak" }, { brand: "Sportiva", weight: "weak" }],
  "4026495": [{ brand: "Schwalbe", weight: "weak" }],
  "4028015": [{ brand: "Heidenau", weight: "weak" }],
  "4710134": [{ brand: "Duro", weight: "weak" }],
  "4717784": [{ brand: "Maxxis", weight: "strong" }, { brand: "CST", weight: "weak" }, { brand: "Cheng Shin", weight: "weak" }, { brand: "Maxxis (Bicycle)", weight: "weak" }],
  "4718022": [{ brand: "Nankang", weight: "strong" }],
  "4961914": [{ brand: "Bridgestone", weight: "weak" }],
  "4962625": [{ brand: "IRC", weight: "weak" }],
  "4968814": [{ brand: "Yokohama", weight: "weak" }],
  "4981910": [{ brand: "Toyo Tires", weight: "strong" }],
  "5060330": [{ brand: "Atturo", weight: "strong" }],
  "6413613": [{ brand: "Nokian", weight: "weak" }],
  "6927116": [{ brand: "Westlake", weight: "weak" }, { brand: "Goodride", weight: "strong" }, { brand: "Chaoyang", weight: "weak" }, { brand: "Arisun", weight: "weak" }],
  "6932877": [{ brand: "Giti", weight: "weak" }],
  "6959458": [{ brand: "Chengshan", weight: "weak" }, { brand: "Austone", weight: "weak" }, { brand: "Sampson", weight: "weak" }, { brand: "Advance", weight: "weak" }],
  "6959654": [{ brand: "Triangle", weight: "weak" }],
  "6959655": [{ brand: "Sailun", weight: "weak" }, { brand: "Rovelo", weight: "weak" }, { brand: "Jinyu", weight: "weak" }],
  "6959656": [{ brand: "Haida", weight: "weak" }, { brand: "Joyroad", weight: "weak" }, { brand: "Mazzini", weight: "weak" }],
  "6959955": [{ brand: "Double Coin", weight: "weak" }, { brand: "Boto", weight: "weak" }, { brand: "Wanda", weight: "weak" }],
  "6959956": [{ brand: "Linglong", weight: "strong" }, { brand: "Leao", weight: "weak" }, { brand: "Atlas", weight: "weak" }, { brand: "Zeta", weight: "weak" }, { brand: "MaxTrek", weight: "weak" }, { brand: "Duraturn", weight: "weak" }, { brand: "SunF", weight: "weak" }],
  "731235": [{ brand: "Trelleborg", weight: "weak" }],
  "7501111": [{ brand: "Tornel", weight: "weak" }],
  "8019227": [{ brand: "Pirelli", weight: "strong", source: "https://www.upcindex.com/8019227414325" }, { brand: "Metzeler", weight: "strong", source: "https://no.product-search.net/80192274" }],
  "8059971": [{ brand: "BKT", weight: "weak" }, { brand: "BKT (Ag)", weight: "weak" }],
  "8590341": [{ brand: "Mitas", weight: "weak" }, { brand: "Mitas (Moto)", weight: "weak" }],
  "8714692": [{ brand: "Vredestein", weight: "weak" }, { brand: "Vredestein (US)", weight: "weak" }],
  "8807622": [{ brand: "Nexen", weight: "strong" }, { brand: "Roadstone", weight: "weak" }],
  "8808569": [{ brand: "Hankook", weight: "weak" }, { brand: "Kingstar", weight: "weak" }],
  "8808922": [{ brand: "Shinko", weight: "weak" }],
  "8808956": [{ brand: "Kumho", weight: "strong" }, { brand: "Marshal", weight: "weak" }],
  "8851123": [{ brand: "Vee Rubber", weight: "weak" }],
  "8858712": [{ brand: "Deestone", weight: "weak" }],
  "8858973": [{ brand: "Otani", weight: "weak" }],
  "8888001": [{ brand: "Radar", weight: "weak" }, { brand: "Patriot", weight: "weak" }, { brand: "American Tourer", weight: "weak" }],
  "8901002": [{ brand: "MRF", weight: "weak" }],
  "8901003": [{ brand: "CEAT", weight: "weak" }],
  "8901004": [{ brand: "JK Tyre", weight: "weak" }],
  "8902823": [{ brand: "Apollo", weight: "weak" }],
  "8936096": [{ brand: "Sailun", weight: "strong" }, { brand: "Rovelo", weight: "weak" }, { brand: "Blackhawk", weight: "weak" }, { brand: "Ironhead", weight: "weak" }, { brand: "RoadX", weight: "weak" }],
  "8997011": [{ brand: "Accelera", weight: "weak" }, { brand: "Forceum", weight: "weak" }],
};
