// GENERATED FILE - do not edit by hand. Source: tire_prefixes_FINAL.csv (validated, tiered).
// Regenerate: node scripts/genTirePrefixHints.mjs
// Ingested as prefixes: hint_strong=252, hint_weak=147 (240 distinct prefixes).
// NOT ingested (held out): exclude_partnumber=7, review_before_use=6.
//
// A prefix may map to a brand FAMILY (corporate siblings sharing a GS1 company prefix). A hint may
// only SUGGEST/BOOST a brand - it NEVER marks a scan known/verified, auto-counts, or overrides the
// firewall. A real confirmed scan promotes a brand<-prefix link to trusted via deriveBrandPrefixHints.

export type PrefixWeight = "strong" | "weak";
export interface PrefixHint { brand: string; weight: PrefixWeight; source?: string }

export const TIRE_PREFIX_HINTS: Record<string, PrefixHint[]> = {
  "00004164861": [{ brand: "Fronway", weight: "strong" }],
  "0000416488": [{ brand: "Toledo", weight: "strong" }],
  "00004169": [{ brand: "Grenlander", weight: "strong" }],
  "0191563": [{ brand: "Nexen", weight: "strong" }],
  "025114": [{ brand: "Carlisle", weight: "weak" }, { brand: "ITP", weight: "weak" }, { brand: "Carlisle (Ag)", weight: "weak" }],
  "029142": [{ brand: "Cooper", weight: "strong" }, { brand: "Mastercraft", weight: "strong", source: "https://www.barcodespider.com/029142694212" }, { brand: "Starfire", weight: "strong", source: "https://www.amazon.com/Starfire-Solarus-Season-Radial-Tire-LT215/dp/B07Y7342PX" }, { brand: "Avon Tyres", weight: "weak" }, { brand: "Arizonian", weight: "weak" }, { brand: "Phantom", weight: "weak" }, { brand: "Dean", weight: "weak" }, { brand: "Oliver (Cooper)", weight: "weak" }],
  "040051": [{ brand: "Delta", weight: "weak" }, { brand: "Eldorado", weight: "weak" }, { brand: "Multi-Mile", weight: "weak" }, { brand: "Cordovan", weight: "weak" }, { brand: "Sigma", weight: "weak" }, { brand: "Vanderbilt", weight: "weak" }, { brand: "Power King", weight: "weak" }, { brand: "Towmax", weight: "weak" }, { brand: "Mud Claw", weight: "weak" }, { brand: "Trail Guide", weight: "weak" }, { brand: "Mirada", weight: "weak" }],
  "045000": [{ brand: "Headway", weight: "strong" }],
  "04501135": [{ brand: "Aplus", weight: "strong" }],
  "045026": [{ brand: "Aplus", weight: "strong" }],
  "045043434": [{ brand: "Gripmax", weight: "strong" }],
  "0450434344": [{ brand: "Roadx", weight: "strong" }],
  "04504465": [{ brand: "Kanati", weight: "strong" }],
  "045063202": [{ brand: "Prinx", weight: "strong" }, { brand: "Roadx", weight: "strong" }, { brand: "Zeta", weight: "strong" }],
  "045065195": [{ brand: "Linglong", weight: "strong" }],
  "045069367": [{ brand: "Prinx", weight: "strong" }],
  "045086": [{ brand: "Forceland", weight: "strong" }],
  "045086267": [{ brand: "Prinx", weight: "strong" }],
  "045086674": [{ brand: "Gripmax", weight: "strong" }],
  "04509030": [{ brand: "Rovelo", weight: "strong" }],
  "045090304": [{ brand: "Samson", weight: "strong" }],
  "04509387": [{ brand: "Linglong", weight: "strong" }],
  "045097370": [{ brand: "Rovelo", weight: "strong" }],
  "04600534828": [{ brand: "Riken", weight: "strong" }],
  "046044": [{ brand: "Gripmax", weight: "strong" }],
  "046047": [{ brand: "Samson", weight: "strong" }],
  "0460476": [{ brand: "Bearway", weight: "strong" }],
  "046055996": [{ brand: "Riken", weight: "strong" }],
  "0461110": [{ brand: "Riken", weight: "strong" }],
  "0461152": [{ brand: "Evergreen", weight: "strong" }],
  "046166": [{ brand: "Eldorado", weight: "strong" }],
  "046173": [{ brand: "Evergreen", weight: "strong" }],
  "04622368": [{ brand: "Nama", weight: "strong" }],
  "04631173": [{ brand: "Lanvigator", weight: "strong" }],
  "04635139": [{ brand: "Lanvigator", weight: "strong" }],
  "04635279": [{ brand: "Petlas", weight: "strong" }],
  "04653201": [{ brand: "Kinforest", weight: "strong" }],
  "046617": [{ brand: "Centara", weight: "strong" }],
  "04666505": [{ brand: "Zenna", weight: "strong" }],
  "047853": [{ brand: "Kenda", weight: "strong" }],
  "051342": [{ brand: "General Tire", weight: "strong" }],
  "054137": [{ brand: "Pirelli", weight: "strong" }],
  "0613365": [{ brand: "Hifly", weight: "strong" }],
  "06363132": [{ brand: "Powertrac", weight: "strong" }],
  "0636313316": [{ brand: "Kpatos", weight: "strong" }],
  "06363133224": [{ brand: "Roadcruza", weight: "strong" }],
  "064112635": [{ brand: "Sailun", weight: "strong" }],
  "0645890": [{ brand: "Rapid", weight: "strong" }],
  "06458907": [{ brand: "Cordovan", weight: "strong" }, { brand: "Blacklion", weight: "strong" }],
  "0661537": [{ brand: "Nankang", weight: "strong" }, { brand: "Goodride", weight: "strong" }, { brand: "Fuzion", weight: "strong" }, { brand: "Nama", weight: "strong" }, { brand: "Doral", weight: "strong" }],
  "0669168904": [{ brand: "Dcenti", weight: "strong" }],
  "06823185": [{ brand: "Doral", weight: "strong" }],
  "0682318568": [{ brand: "Sumic", weight: "strong" }],
  "0682318620": [{ brand: "Zeetex", weight: "strong" }],
  "0686162903": [{ brand: "Lande", weight: "strong" }],
  "0688028": [{ brand: "Hercules", weight: "strong" }, { brand: "Ironman", weight: "strong" }, { brand: "Dynatrac (ATD)", weight: "weak" }],
  "069067731": [{ brand: "Dean", weight: "strong" }],
  "06939801740": [{ brand: "Rolling Big Power Tires", weight: "strong" }],
  "0696449": [{ brand: "Jinyu", weight: "strong" }, { brand: "Boto", weight: "strong" }, { brand: "Constancy", weight: "strong" }, { brand: "Sunfull", weight: "strong" }, { brand: "Sumic", weight: "strong" }, { brand: "Geostar", weight: "strong" }],
  "069644963": [{ brand: "Roadstone", weight: "strong" }],
  "069661209": [{ brand: "Fury", weight: "strong" }],
  "069766": [{ brand: "Dunlop", weight: "strong" }, { brand: "Kelly", weight: "weak" }, { brand: "Debica", weight: "weak" }, { brand: "Sava", weight: "weak" }, { brand: "Fulda", weight: "weak" }, { brand: "Fierce", weight: "weak" }, { brand: "Remington", weight: "weak" }, { brand: "Monarch", weight: "weak" }, { brand: "Lee", weight: "weak" }, { brand: "Republic", weight: "weak" }],
  "0703382": [{ brand: "Nokian", weight: "strong" }],
  "071477061": [{ brand: "Ohtsu", weight: "strong" }],
  "0714770701": [{ brand: "Triangle", weight: "strong" }],
  "0715459": [{ brand: "Hankook", weight: "strong" }, { brand: "Laufenn", weight: "weak" }, { brand: "Pathfinder", weight: "weak" }],
  "0721506": [{ brand: "Yokohama", weight: "strong" }, { brand: "Alliance", weight: "weak" }, { brand: "Galaxy", weight: "weak" }, { brand: "Galaxy (Ag)", weight: "weak" }, { brand: "Primex (Ag)", weight: "weak" }],
  "0721749": [{ brand: "Nankang", weight: "strong" }, { brand: "Neoterra", weight: "strong" }],
  "072439113": [{ brand: "Lexani", weight: "strong" }],
  "0724391159": [{ brand: "Ohtsu", weight: "strong" }],
  "0729419": [{ brand: "Amp", weight: "strong" }],
  "0733569": [{ brand: "Dean", weight: "strong" }, { brand: "Presa", weight: "strong" }, { brand: "Rapid", weight: "strong" }, { brand: "Blacklion", weight: "strong" }, { brand: "Dcenti", weight: "strong" }, { brand: "Evoluxx", weight: "strong" }],
  "07335696": [{ brand: "Linglong", weight: "strong" }],
  "0737245": [{ brand: "Kanati", weight: "strong" }],
  "07413170": [{ brand: "Westlake", weight: "strong" }],
  "07413179": [{ brand: "Kelly", weight: "strong" }],
  "074131795": [{ brand: "Fierce", weight: "strong" }],
  "074131796": [{ brand: "Douglas", weight: "strong" }],
  "074146662": [{ brand: "Vitour", weight: "strong" }],
  "0741466620": [{ brand: "Vanderbilt", weight: "strong" }],
  "0741466645": [{ brand: "Rapid", weight: "strong" }],
  "074242797": [{ brand: "Lionhart", weight: "strong" }],
  "0746573": [{ brand: "Cordovan", weight: "strong" }, { brand: "Multimile", weight: "strong" }],
  "07465732": [{ brand: "Advanta", weight: "strong" }, { brand: "Sumitomo", weight: "strong" }],
  "0749715": [{ brand: "Crosswind", weight: "strong" }],
  "0753760792": [{ brand: "Constancy", weight: "strong" }],
  "0757558743": [{ brand: "Rolling Big Power Tires", weight: "strong" }],
  "075839986": [{ brand: "Winda", weight: "strong" }],
  "0758823": [{ brand: "Westlake", weight: "strong" }, { brand: "Milestar", weight: "strong" }, { brand: "Nankang (NA)", weight: "weak" }, { brand: "Freestar", weight: "weak" }, { brand: "Pro-Meter", weight: "weak" }, { brand: "Geostar", weight: "weak" }, { brand: "Geotrac", weight: "weak" }],
  "0762530": [{ brand: "Freestar", weight: "strong" }],
  "0765105499": [{ brand: "Lexani", weight: "strong" }],
  "0768155": [{ brand: "Sumitomo", weight: "strong" }],
  "0779283231": [{ brand: "Versatyre", weight: "strong" }],
  "0782731718": [{ brand: "Deestone", weight: "strong" }],
  "0787025": [{ brand: "Mickey Thompson", weight: "strong" }, { brand: "Dick Cepek", weight: "weak" }],
  "081002282": [{ brand: "Mrf", weight: "strong" }],
  "081004539": [{ brand: "Mrf", weight: "strong" }],
  "0810045390": [{ brand: "Barum", weight: "strong" }],
  "0810047080": [{ brand: "Cosmo", weight: "strong" }],
  "081013040": [{ brand: "Kapsen", weight: "strong" }, { brand: "Tornel", weight: "strong" }, { brand: "Farroad", weight: "strong" }, { brand: "Mrf", weight: "strong" }],
  "0810130406": [{ brand: "Evoluxx", weight: "strong" }],
  "08101304093": [{ brand: "Bearway", weight: "strong" }],
  "0810136810": [{ brand: "Winda", weight: "strong" }],
  "0810149131": [{ brand: "Gripmax", weight: "strong" }],
  "0810176311": [{ brand: "Trailfinder", weight: "strong" }],
  "081229102": [{ brand: "Rydanz", weight: "strong" }],
  "081256102": [{ brand: "Travelstar", weight: "strong" }],
  "081434202": [{ brand: "Roadone", weight: "strong" }],
  "0816456028": [{ brand: "Diamondback", weight: "strong" }],
  "0818749": [{ brand: "GT Radial", weight: "strong" }, { brand: "Primewell", weight: "weak" }, { brand: "Dextero", weight: "weak" }, { brand: "Dynatrac", weight: "weak" }],
  "0819169020": [{ brand: "Supermax", weight: "strong" }],
  "0826825": [{ brand: "Toyo Tires (NA)", weight: "weak" }, { brand: "Nitto", weight: "strong" }],
  "0826826": [{ brand: "Sumitomo", weight: "strong" }, { brand: "Doral", weight: "weak" }, { brand: "Solar", weight: "weak" }],
  "08401396": [{ brand: "Fortune", weight: "strong" }, { brand: "Prinx", weight: "weak" }],
  "0840156": [{ brand: "Atturo", weight: "strong" }, { brand: "Lexani", weight: "weak" }, { brand: "Lionhart", weight: "weak" }, { brand: "Arroyo", weight: "weak" }, { brand: "Venom Power", weight: "weak" }, { brand: "Fury", weight: "weak" }, { brand: "Transeagle", weight: "weak" }, { brand: "Gladiator", weight: "weak" }, { brand: "Zenna", weight: "weak" }],
  "08414381": [{ brand: "Duraturn", weight: "strong" }],
  "084161110": [{ brand: "Grenlander", weight: "strong" }],
  "0841623": [{ brand: "Sentury", weight: "weak" }, { brand: "Delinte", weight: "strong" }, { brand: "Landsail", weight: "weak" }, { brand: "Groundspeed", weight: "weak" }, { brand: "Pantera", weight: "weak" }, { brand: "American Roadstar", weight: "strong" }],
  "084187710": [{ brand: "Windforce", weight: "strong" }],
  "084214": [{ brand: "Coker Tire", weight: "weak" }],
  "084216": [{ brand: "Lionhart", weight: "strong" }],
  "08421641": [{ brand: "Jinyu", weight: "strong" }],
  "08422100": [{ brand: "Sumitomo", weight: "strong" }],
  "08444020": [{ brand: "Gladiator", weight: "strong" }, { brand: "Advanta", weight: "strong" }],
  "0848983": [{ brand: "Falken", weight: "strong" }, { brand: "Ohtsu", weight: "strong", source: "https://www.u-buy.com.ng/product/2MPGKEFI-ohtsu-fp8000-all-season-radial-tire-28525zr20-93w" }, { brand: "Wild Spirit", weight: "weak" }, { brand: "Wild Country", weight: "weak" }],
  "08498490": [{ brand: "Antares", weight: "strong" }, { brand: "Maxtrek", weight: "strong" }],
  "0850000023": [{ brand: "Mrf", weight: "strong" }],
  "085532": [{ brand: "Vogue", weight: "weak" }],
  "086699": [{ brand: "Michelin", weight: "strong" }, { brand: "BFGoodrich", weight: "strong" }, { brand: "Uniroyal (US)", weight: "strong" }, { brand: "Oliver", weight: "weak" }],
  "087718400": [{ brand: "Falken", weight: "strong" }, { brand: "Ohtsu Tires", weight: "strong" }],
  "0877184008": [{ brand: "Ohtsu", weight: "strong" }],
  "088656": [{ brand: "Titan", weight: "weak" }],
  "0887613": [{ brand: "Nexen", weight: "strong" }, { brand: "Roadstone", weight: "strong" }],
  "08881350": [{ brand: "Triangle", weight: "strong" }],
  "092971": [{ brand: "Bridgestone", weight: "strong" }, { brand: "Firestone", weight: "strong" }, { brand: "Dayton", weight: "weak" }, { brand: "Fuzion", weight: "strong", source: "https://www.upcindex.com/92971317478" }, { brand: "Bandag", weight: "weak" }],
  "098663": [{ brand: "Kenda", weight: "strong" }],
  "09904986": [{ brand: "Rotalla", weight: "strong" }, { brand: "Minerva", weight: "strong" }, { brand: "Mirage", weight: "strong" }, { brand: "Ovation", weight: "strong" }],
  "2001214408": [{ brand: "Gislaved", weight: "strong" }],
  "2001214459": [{ brand: "Mirage", weight: "strong" }],
  "200121449": [{ brand: "Toledo", weight: "strong" }],
  "20012145012": [{ brand: "Dean", weight: "strong" }],
  "2001214508": [{ brand: "Minerva", weight: "strong" }],
  "352870": [{ brand: "Michelin", weight: "weak" }, { brand: "Kleber", weight: "weak" }, { brand: "Tigar", weight: "weak" }, { brand: "Riken", weight: "weak" }, { brand: "Kormoran", weight: "weak" }, { brand: "Sebring", weight: "weak" }, { brand: "Siamtyre", weight: "weak" }],
  "4010684": [{ brand: "Falken (EU)", weight: "weak" }],
  "4019238": [{ brand: "Continental", weight: "strong" }, { brand: "Uniroyal (EU)", weight: "weak" }, { brand: "Semperit", weight: "weak" }, { brand: "Barum", weight: "weak" }, { brand: "Viking", weight: "weak" }, { brand: "Gislaved", weight: "weak" }, { brand: "Euzkadi", weight: "weak" }, { brand: "General", weight: "weak" }, { brand: "Sportiva", weight: "weak" }],
  "4024063": [{ brand: "Barum", weight: "strong" }],
  "4026495": [{ brand: "Schwalbe", weight: "weak" }],
  "4028015": [{ brand: "Heidenau", weight: "weak" }],
  "425008467": [{ brand: "Syron", weight: "strong" }],
  "4710134": [{ brand: "Duro", weight: "weak" }],
  "47104054": [{ brand: "Kenda", weight: "strong" }],
  "47110415": [{ brand: "Kenda", weight: "strong" }],
  "47133091": [{ brand: "Kenda", weight: "strong" }],
  "4713959": [{ brand: "Federal", weight: "strong" }],
  "471395900": [{ brand: "Atturo", weight: "strong" }],
  "4717294": [{ brand: "Kenda", weight: "strong" }],
  "4717784": [{ brand: "Maxxis", weight: "strong" }, { brand: "CST", weight: "weak" }, { brand: "Cheng Shin", weight: "weak" }, { brand: "Maxxis (Bicycle)", weight: "weak" }],
  "4718022": [{ brand: "Nankang", weight: "strong" }],
  "4961914": [{ brand: "Bridgestone", weight: "weak" }],
  "4962625": [{ brand: "IRC", weight: "weak" }],
  "4968814": [{ brand: "Yokohama", weight: "weak" }],
  "4981910": [{ brand: "Toyo Tires", weight: "strong" }],
  "5060330": [{ brand: "Atturo", weight: "strong" }],
  "542006867": [{ brand: "Goform", weight: "strong" }],
  "542006868": [{ brand: "Superia", weight: "strong" }],
  "5452000": [{ brand: "Fulda", weight: "strong" }],
  "62903000": [{ brand: "Zeetex", weight: "strong" }],
  "6413613": [{ brand: "Nokian", weight: "weak" }],
  "6419440": [{ brand: "Nokian", weight: "strong" }],
  "6900532": [{ brand: "Landsail", weight: "strong" }],
  "6901532": [{ brand: "Delinte", weight: "strong" }],
  "690168101": [{ brand: "Joyroad", weight: "strong" }],
  "69053220": [{ brand: "Haida", weight: "strong" }],
  "692110901": [{ brand: "Lexani", weight: "strong" }, { brand: "Lionhart", weight: "strong" }],
  "692225040": [{ brand: "Jinyu", weight: "strong" }],
  "692406410": [{ brand: "Aplus", weight: "strong" }],
  "692459021": [{ brand: "Mazzini", weight: "strong" }],
  "6927116": [{ brand: "Westlake", weight: "weak" }, { brand: "Goodride", weight: "strong" }, { brand: "Chaoyang", weight: "weak" }, { brand: "Arisun", weight: "weak" }],
  "6932877": [{ brand: "Giti", weight: "weak" }],
  "693862820": [{ brand: "Constancy", weight: "strong" }],
  "69398017": [{ brand: "Comforser", weight: "strong" }],
  "694265991": [{ brand: "Roadlux", weight: "strong" }],
  "69503063": [{ brand: "Sunny", weight: "strong" }],
  "695391310": [{ brand: "Hifly", weight: "strong" }],
  "695391312": [{ brand: "Sunfull", weight: "strong" }],
  "6959458": [{ brand: "Chengshan", weight: "weak" }, { brand: "Austone", weight: "weak" }, { brand: "Sampson", weight: "weak" }, { brand: "Advance", weight: "weak" }],
  "695961370": [{ brand: "Keter", weight: "strong" }],
  "695961372": [{ brand: "Neoterra", weight: "strong" }],
  "6959654": [{ brand: "Triangle", weight: "weak" }],
  "6959655": [{ brand: "Sailun", weight: "weak" }, { brand: "Rovelo", weight: "weak" }, { brand: "Jinyu", weight: "weak" }],
  "6959656": [{ brand: "Haida", weight: "weak" }, { brand: "Joyroad", weight: "weak" }, { brand: "Mazzini", weight: "weak" }],
  "6959955": [{ brand: "Double Coin", weight: "weak" }, { brand: "Boto", weight: "weak" }, { brand: "Wanda", weight: "weak" }],
  "6959956": [{ brand: "Linglong", weight: "strong" }, { brand: "Leao", weight: "weak" }, { brand: "Atlas", weight: "weak" }, { brand: "Zeta", weight: "weak" }, { brand: "MaxTrek", weight: "weak" }, { brand: "Duraturn", weight: "weak" }, { brand: "SunF", weight: "weak" }],
  "6970004901": [{ brand: "Windforce", weight: "strong" }],
  "697014611": [{ brand: "Winrun", weight: "strong" }],
  "697014945": [{ brand: "Powertrac", weight: "strong" }],
  "697159410": [{ brand: "Compasal", weight: "strong" }],
  "697250864": [{ brand: "Compasal", weight: "strong" }],
  "731235": [{ brand: "Trelleborg", weight: "weak" }],
  "7465734": [{ brand: "Fuel Tires", weight: "strong" }],
  "7501111": [{ brand: "Tornel", weight: "weak" }],
  "750172050": [{ brand: "Tornel", weight: "strong" }],
  "8019227": [{ brand: "Pirelli", weight: "strong", source: "https://www.upcindex.com/8019227414325" }, { brand: "Metzeler", weight: "strong", source: "https://no.product-search.net/80192274" }],
  "805645024": [{ brand: "Momo", weight: "strong" }],
  "8059971": [{ brand: "BKT", weight: "weak" }, { brand: "BKT (Ag)", weight: "weak" }],
  "8498490": [{ brand: "Antares", weight: "strong" }],
  "8590341": [{ brand: "Mitas", weight: "weak" }, { brand: "Mitas (Moto)", weight: "weak" }],
  "868111066": [{ brand: "Arroyo", weight: "strong" }, { brand: "Waterfall", weight: "strong" }],
  "8714692": [{ brand: "Vredestein", weight: "weak" }, { brand: "Vredestein (US)", weight: "weak" }],
  "8807622": [{ brand: "Nexen", weight: "strong" }, { brand: "Roadstone", weight: "weak" }],
  "8808569": [{ brand: "Hankook", weight: "weak" }, { brand: "Kingstar", weight: "weak" }],
  "8808922": [{ brand: "Shinko", weight: "weak" }],
  "8808956": [{ brand: "Kumho", weight: "strong" }, { brand: "Marshal", weight: "weak" }],
  "88481160": [{ brand: "Blackhawk", weight: "strong" }],
  "8851123": [{ brand: "Vee Rubber", weight: "weak" }],
  "8858712": [{ brand: "Deestone", weight: "weak" }],
  "8858973": [{ brand: "Otani", weight: "weak" }],
  "88591054": [{ brand: "Thunderer", weight: "strong" }],
  "885910541": [{ brand: "Cosmo", weight: "strong" }],
  "88592914": [{ brand: "Crosswind", weight: "strong" }, { brand: "Leao", weight: "strong" }],
  "885929141": [{ brand: "Atlas", weight: "strong" }],
  "88592958": [{ brand: "Lexani", weight: "strong" }, { brand: "Arroyo", weight: "strong" }],
  "88593055": [{ brand: "Trazano", weight: "strong" }, { brand: "Arisun", weight: "strong" }],
  "88593849": [{ brand: "Otani", weight: "strong" }],
  "88864595": [{ brand: "Radar", weight: "strong" }, { brand: "Patriot", weight: "strong" }],
  "8888001": [{ brand: "Radar", weight: "weak" }, { brand: "Patriot", weight: "weak" }, { brand: "American Tourer", weight: "weak" }],
  "8901002": [{ brand: "MRF", weight: "weak" }],
  "8901003": [{ brand: "CEAT", weight: "weak" }],
  "8901004": [{ brand: "JK Tyre", weight: "weak" }],
  "8902823": [{ brand: "Apollo", weight: "weak" }],
  "89353412": [{ brand: "Blackhawk", weight: "strong" }],
  "8936096": [{ brand: "Sailun", weight: "strong" }, { brand: "Rovelo", weight: "weak" }, { brand: "Blackhawk", weight: "weak" }, { brand: "Ironhead", weight: "weak" }, { brand: "RoadX", weight: "weak" }],
  "893620692": [{ brand: "Advance", weight: "strong" }],
  "8938539571": [{ brand: "Advance", weight: "strong" }],
  "899423402": [{ brand: "Accelera", weight: "strong" }],
  "89947310": [{ brand: "Achilles", weight: "strong" }],
  "8997011": [{ brand: "Accelera", weight: "weak" }, { brand: "Forceum", weight: "weak" }],
  "899702061": [{ brand: "Accelera", weight: "strong" }],
  "955000000": [{ brand: "Versatyre", weight: "strong" }, { brand: "Fullway", weight: "strong" }],
  "99049864": [{ brand: "Rotalla", weight: "strong" }],
};
