// e2e/virtual-shops/drivers/legacy-tires.mjs
//
// Virtual shop (c) "Legacy Tires" - the "we found you $X" demo generator.
// See shops.config.mjs; retired design history is summarized in docs/HISTORY.md.
//
// Flow (real UI, mock backend only):
//   1. Import the pre-committed, ugly legacy-style spreadsheet
//      (fixtures/legacy-tires-level5.csv, generated by
//      fixtures/generate-fixtures.mjs via e2e/teach/sheets.mjs, checked in
//      for determinism) through the real Universal Import flow on
//      /products. This is the design doc's "import ... book count" step; it
//      also registers each SKU's barcode in the catalog.
//   2. Physically scan the achievable variance on top of the import: for
//      every fixtures/legacy-tires-ground-truth.json perProduct entry whose
//      seeded physicalQuantity exceeds its bookQuantity (and that has a
//      barcode to scan), scan the difference on /scan - "found extra stock
//      on the shelf". A physicalQuantity BELOW bookQuantity cannot be
//      reproduced by scan-only means (scanning never reduces a count) - see
//      "Known limitation" below; that SKU is flagged, never silently faked.
//   3. Generate a records CSV from the ground truth's bookQuantity per SKU
//      (via e2e/teach/sheets.mjs's generateShopwareCsv, reused as-is) and
//      run it through the real Reconcile flow on /reconcile.
//   4. Extract the rendered variance buckets from the DOM for evidence.
//   5. Write a demo-ready markdown report: "Records say N, counted M, ~$X
//      variance across K SKUs" - including the ground truth's pre-committed
//      dollar variance and any documented gap between seed and what a
//      scan-only harness can physically reproduce.
//
// Known limitation (documented, not silently papered over): the ground
// truth's "expected_not_counted" SKU (General AltiMAX RT43: book 9, physical
// 0) also has no barcode in the fixture, so this scan-only harness can
// neither push it up nor down by scanning - it stays at whatever the import
// establishes. This is logged as a report limitation rather than faked.
//
// Falls back to generating an equivalent messy spreadsheet + ground truth at
// runtime (the same 8-product shape this driver used before it was wired to
// the checked-in fixtures) if either fixture file is missing or unreadable,
// so the driver stays runnable standalone.
//
// Mock-only: /api/ai-lookup is routed to a local stub via
// drivers/_shared.mjs's installMockAiRoute; AI lookup is also disabled
// through app settings before anything is scanned. Restricted to
// localhost:3500 (drivers/_shared.mjs validateLocalTarget), the port
// reserved for virtual shops in the design doc.

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";
import { chromium } from "playwright";
import { generateInventorySheet, generateShopwareCsv } from "../../teach/sheets.mjs";
import {
  DEFAULT_TARGET,
  artifactPath,
  ensureDir,
  installMockAiRoute,
  loginAndReachScan,
  scanCode,
  validateLocalTarget,
} from "./_shared.mjs";

const KNOWN_BUCKETS = [
  "agreement",
  "variance",
  "expected_not_counted",
  "ambiguous",
  "unmatched",
  "non_tire",
  "uom_review",
  "unparseable",
];

const DEFAULT_CSV_FIXTURE = resolve(process.cwd(), "e2e/virtual-shops/fixtures/legacy-tires-level5.csv");
const DEFAULT_GROUND_TRUTH_FIXTURE = resolve(
  process.cwd(),
  "e2e/virtual-shops/fixtures/legacy-tires-ground-truth.json",
);

// Standalone fallback used only when one of the two committed fixtures is
// missing or unreadable. Same 8-product shape this driver used before it was
// wired to the checked-in fixtures.
const FALLBACK_PRODUCTS = [
  { partNumber: "28034300", brand: "Falken", model: "Wildpeak A/T3W", size: "265/70R17", barcode: "848983006257", bookQty: 6, importQty: 6, scanExtra: 0, unitCost: 145.0 },
  { partNumber: "90000027117", brand: "Cooper", model: "Discoverer SRX", size: "265/70R17", barcode: "029142869870", bookQty: 4, importQty: 4, scanExtra: 2, unitCost: 128.5 },
  { partNumber: "44953", brand: "Michelin", model: "Premier LTX", size: "225/65R17", barcode: "086699449535", bookQty: 8, importQty: 5, scanExtra: 0, unitCost: 162.0 },
  { partNumber: "142367", brand: "Bridgestone", model: "Dueler H/P Sport AS", size: "225/65R17", barcode: "092971251802", bookQty: 5, importQty: 5, scanExtra: 0, unitCost: 138.75 },
  { partNumber: "15493460000", brand: "Continental", model: "ProContact TX", size: "235/60R18", barcode: "051342150847", bookQty: 3, importQty: 3, scanExtra: 1, unitCost: 121.0 },
  { partNumber: "3655800", brand: "Pirelli", model: "Cinturato P7 All Season", size: "235/55R18", barcode: "054137079934", bookQty: 7, importQty: 3, scanExtra: 0, unitCost: 175.25 },
  { partNumber: "2159273", brand: "Kumho", model: "Eco Solus KL21", size: "225/65R17", barcode: "8808956132873", bookQty: 2, importQty: 2, scanExtra: 0, unitCost: 99.99 },
  { partNumber: "18773NXK", brand: "Nexen", model: "Roadian ATX", size: "265/70R17", barcode: "191563016307", bookQty: 5, importQty: 5, scanExtra: 2, unitCost: 110.0 },
];

function computeFallbackVariance(products) {
  const rows = products.map((p) => {
    const finalQty = p.importQty + p.scanExtra;
    const deltaUnits = finalQty - p.bookQty;
    return { ...p, finalQty, deltaUnits, deltaDollars: Math.round(deltaUnits * p.unitCost * 100) / 100 };
  });
  const varianceRows = rows.filter((r) => r.deltaUnits !== 0);
  const totalDollarVariance =
    Math.round(varianceRows.reduce((sum, r) => sum + Math.abs(r.deltaDollars), 0) * 100) / 100;
  return { rows, totalDollarVariance };
}

function parseArgs(argv) {
  const values = {
    target: DEFAULT_TARGET,
    outputDir: "reports/virtual-shops/legacy-tires",
    csvFixture: DEFAULT_CSV_FIXTURE,
    groundTruthFixture: DEFAULT_GROUND_TRUTH_FIXTURE,
  };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--target") values.target = argv[++index];
    else if (argument === "--output-dir") values.outputDir = argv[++index];
    else if (argument === "--csv-fixture") values.csvFixture = argv[++index];
    else if (argument === "--ground-truth-fixture") values.groundTruthFixture = argv[++index];
    else if (argument === "--help") {
      console.log(
        "Usage: node e2e/virtual-shops/drivers/legacy-tires.mjs [--target http://localhost:3500] " +
          "[--output-dir reports/virtual-shops/legacy-tires] [--csv-fixture path.csv] " +
          "[--ground-truth-fixture path.json]",
      );
      process.exit(0);
    } else throw new Error(`Unknown argument: ${argument}`);
  }
  if (!values.target || !values.outputDir) throw new Error("--target and --output-dir need values");
  values.target = validateLocalTarget(values.target);
  return values;
}

async function readReconcileReport(page) {
  const rows = [];
  for (const bucket of KNOWN_BUCKETS) {
    const section = page.getByTestId(`bucket-${bucket}`);
    const visible = await section.isVisible({ timeout: 1000 }).catch(() => false);
    if (!visible) continue;
    const bodyRows = section.locator("tbody tr");
    const rowCount = await bodyRows.count().catch(() => 0);
    for (let i = 0; i < rowCount; i += 1) {
      const row = bodyRows.nth(i);
      const cells = row.locator("td");
      const cellCount = await cells.count().catch(() => 0);
      const cellTexts = [];
      for (let c = 0; c < cellCount; c += 1) {
        cellTexts.push((await cells.nth(c).innerText().catch(() => "")).trim());
      }
      const deltaText = (await row.getByTestId("reconcile-delta").innerText().catch(() => "")).trim();
      rows.push({ bucket, partNumbers: cellTexts[0] ?? "", delta: deltaText });
    }
  }
  return rows;
}

function findAppRow(reportRows, partNumber) {
  const needle = String(partNumber).toLowerCase();
  return reportRows.find((r) => r.partNumbers.toLowerCase().includes(needle));
}

function moneyFmt(value) {
  const sign = value < 0 ? "-" : "";
  return `${sign}$${Math.abs(value).toFixed(2)}`;
}

async function loadFixtures(csvFixturePath, groundTruthFixturePath) {
  try {
    await readFile(csvFixturePath, "utf8");
    const groundTruthRaw = await readFile(groundTruthFixturePath, "utf8");
    const groundTruth = JSON.parse(groundTruthRaw);
    if (!Array.isArray(groundTruth.perProduct)) throw new Error("ground truth fixture missing perProduct[]");
    return { mode: "fixture", csvFixturePath, groundTruth };
  } catch (error) {
    return { mode: "fallback", reason: error instanceof Error ? error.message : String(error) };
  }
}

async function buildDemoMarkdown({ mode, recordsTotal, countedTotal, totalDollarVariance, rows, appBuckets, runId, target, limitations }) {
  const lines = [];
  lines.push("# Legacy Tires - \"We found you money\" variance report");
  lines.push("");
  lines.push(`Run: ${runId}`);
  lines.push(`Target: ${target} (mock backend only)`);
  lines.push(
    `Data source: ${
      mode === "fixture"
        ? "checked-in fixtures (legacy-tires-level5.csv + legacy-tires-ground-truth.json)"
        : "runtime-generated fallback (fixtures unavailable)"
    }`,
  );
  lines.push("");
  lines.push(
    `**Records say ${recordsTotal} units. We counted ${countedTotal}. ` +
      `That's ${moneyFmt(totalDollarVariance)} in variance across ${rows.filter((r) => r.deltaUnits !== 0).length} SKUs.**`,
  );
  lines.push("");
  lines.push(
    "Records = the shop's book/records file, run through the app's real Reconcile flow. " +
      "Counted = physical quantities the app has on hand today, from an imported first-pass " +
      "spreadsheet plus a follow-up physical scan of a few SKUs. Every dollar figure below is " +
      "computed from local fixture data - nothing about pricing or cost is ever sent to the app " +
      "or any network call.",
  );
  lines.push("");
  lines.push("## Variance detail");
  lines.push("");
  lines.push("| SKU | Book Qty | Counted Qty | Delta (units) | Unit Cost | Delta ($) | App bucket |");
  lines.push("|---|---|---|---|---|---|---|");
  for (const row of rows) {
    const appRow = findAppRow(appBuckets, row.partNumber);
    lines.push(
      `| ${row.partNumber || row.key} | ${row.bookQty} | ${row.finalQty} | ` +
        `${row.deltaUnits > 0 ? "+" : ""}${row.deltaUnits} | $${row.unitCost.toFixed(2)} | ${moneyFmt(row.deltaDollars)} | ` +
        `${appRow ? appRow.bucket : "(not found in report)"} |`,
    );
  }
  lines.push("");
  if (limitations.length > 0) {
    lines.push("## Known limitations for this run");
    lines.push("");
    for (const limitation of limitations) lines.push(`- ${limitation}`);
    lines.push("");
  }
  lines.push("## Method");
  lines.push("");
  lines.push(
    "1. Imported the ugly legacy spreadsheet (checked-in fixture or runtime fallback) through the real Universal Import flow on `/products`.",
  );
  lines.push("2. Physically scanned the achievable part of the seeded variance on `/scan`, on top of the import.");
  lines.push(
    "3. Generated a records file from the ground-truth book quantities and ran it through the real Reconcile flow on `/reconcile`.",
  );
  lines.push("4. Read the rendered variance buckets from the report UI as evidence (`App bucket` column above).");
  lines.push("5. Reported the ground truth's pre-committed dollar variance alongside any documented gap.");
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const runId = new Date().toISOString().replace(/[:.]/g, "-");
  const runDir = resolve(process.cwd(), options.outputDir, runId);
  const screenshotsDir = resolve(runDir, "screenshots");
  await ensureDir(screenshotsDir);

  const fixtures = await loadFixtures(options.csvFixture, options.groundTruthFixture);

  const report = {
    target: options.target,
    runId,
    data_source: fixtures.mode,
    fixture_fallback_reason: fixtures.mode === "fallback" ? fixtures.reason : null,
    records_total: 0,
    counted_total: 0,
    total_dollar_variance: 0,
    variance_sku_count: 0,
    per_sku: [],
    app_reconcile_rows: [],
    screenshots: [],
    limitations: [],
    failures: [],
  };

  let browser;
  let importFilePath;
  let recordsCsvPath;
  let rows;
  const limitations = [];

  try {
    if (fixtures.mode === "fixture") {
      importFilePath = fixtures.csvFixturePath;
      const recordsProducts = fixtures.groundTruth.perProduct.map((p) => ({
        partNumber: p.partNumber,
        brand: "",
        model: p.name,
        size: "",
        barcode: p.barcode,
        quantity: p.bookQuantity,
      }));
      const recordsCsv = await generateShopwareCsv({
        products: recordsProducts,
        outDir: runDir,
        fileBase: "legacy-records-from-fixture",
      });
      recordsCsvPath = recordsCsv.filePath;

      rows = fixtures.groundTruth.perProduct.map((p) => {
        const deltaUnits = p.physicalQuantity - p.bookQuantity;
        const achievableExtra = p.barcode && deltaUnits > 0 ? deltaUnits : 0;
        if (deltaUnits !== 0 && achievableExtra === 0) {
          const reason = !p.barcode
            ? "no barcode in the fixture - cannot be scanned at all"
            : "target physical count is below the imported book count - scanning cannot reduce a count";
          limitations.push(
            `${p.name} (${p.partNumber || p.key}): seeded physicalQuantity ${p.physicalQuantity} vs book ${p.bookQuantity} ` +
              `not fully reproducible by scan-only means (${reason}); app will show the imported book quantity, not the seeded physical quantity`,
          );
        }
        const finalQty = p.bookQuantity + achievableExtra;
        const achievedDeltaUnits = finalQty - p.bookQuantity;
        return {
          key: p.key,
          partNumber: p.partNumber,
          barcode: p.barcode,
          bookQty: p.bookQuantity,
          finalQty,
          deltaUnits: achievedDeltaUnits,
          deltaDollars: Math.round(achievedDeltaUnits * p.unitPrice * 100) / 100,
          unitCost: p.unitPrice,
          scanExtra: achievableExtra,
        };
      });
    } else {
      const bookSheet = await generateInventorySheet({
        level: 5,
        products: FALLBACK_PRODUCTS.map((p) => ({
          partNumber: p.partNumber,
          brand: p.brand,
          model: p.model,
          size: p.size,
          quantity: p.importQty,
          barcode: p.barcode,
          name: `${p.brand} ${p.model}`,
        })),
        outDir: runDir,
        fileBase: "legacy-book",
      });
      importFilePath = bookSheet.filePath;

      const groundTruthCsv = await generateShopwareCsv({
        products: FALLBACK_PRODUCTS.map((p) => ({
          partNumber: p.partNumber,
          brand: p.brand,
          model: p.model,
          size: p.size,
          barcode: p.barcode,
          quantity: p.bookQty,
        })),
        outDir: runDir,
        fileBase: "legacy-ground-truth",
      });
      recordsCsvPath = groundTruthCsv.filePath;

      const expected = computeFallbackVariance(FALLBACK_PRODUCTS);
      rows = expected.rows.map((r) => ({
        key: r.partNumber,
        partNumber: r.partNumber,
        barcode: r.barcode,
        bookQty: r.bookQty,
        finalQty: r.finalQty,
        deltaUnits: r.deltaUnits,
        deltaDollars: r.deltaDollars,
        unitCost: r.unitCost,
        scanExtra: r.scanExtra,
      }));
    }

    report.records_total = rows.reduce((sum, r) => sum + r.bookQty, 0);
    report.limitations = limitations;

    browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({ acceptDownloads: true });
    const page = await context.newPage();
    page.on("pageerror", (error) => report.failures.push(`page error: ${error.message}`));
    await installMockAiRoute(context);

    await loginAndReachScan(page, options.target);
    await page.evaluate(() => {
      window.__scanStore.getState().updateSettings({ autoSuggestUnknowns: false });
    });

    // --- Step 1: import the (fixture or fallback) legacy spreadsheet through the real Universal Import flow.
    await page.goto(`${options.target}/products`, { waitUntil: "domcontentloaded" });
    await page.getByTestId("universal-import-file").setInputFiles(importFilePath);
    const preview = await Promise.race([
      page.getByTestId("import-preview").waitFor({ state: "visible", timeout: 15_000 }).then(() => "preview"),
      page.getByTestId("column-mapping").waitFor({ state: "visible", timeout: 15_000 }).then(() => "mapping"),
    ]);
    if (preview === "mapping") {
      const confirmButton = page.getByTestId("mapping-confirm");
      if (await confirmButton.isVisible({ timeout: 2000 }).catch(() => false)) await confirmButton.click();
    }
    const importErrorVisible = await page.getByTestId("import-error").isVisible({ timeout: 1000 }).catch(() => false);
    if (importErrorVisible) throw new Error("import-error was visible on the legacy spreadsheet");
    const importPreviewShot = resolve(screenshotsDir, "01-import-preview.png");
    await page.screenshot({ path: importPreviewShot, fullPage: true });
    report.screenshots.push(artifactPath(importPreviewShot));
    await page.getByTestId("import-apply").click();
    await page.getByTestId("import-summary").waitFor({ state: "visible", timeout: 15_000 });

    // --- Step 2: physically scan the achievable variance subset on top of the import.
    await page.goto(`${options.target}/scan`, { waitUntil: "domcontentloaded" });
    await page.getByTestId("scanner-input").waitFor({ timeout: 30_000 });
    for (const row of rows) {
      if (!row.barcode || !row.scanExtra) continue;
      for (let i = 0; i < row.scanExtra; i += 1) await scanCode(page, row.barcode);
    }
    const totalExtraScans = rows.reduce((sum, r) => sum + (r.scanExtra || 0), 0);
    if (totalExtraScans > 0) {
      await page.waitForFunction((min) => window.__scanStore.getState().scanFeed.length >= min, totalExtraScans);
    }

    // --- Step 3: run the records file (derived from the ground truth) through the real Reconcile flow.
    await page.goto(`${options.target}/reconcile`, { waitUntil: "domcontentloaded" });
    await page.getByTestId("reconcile-file").setInputFiles(recordsCsvPath);
    await page.getByTestId("reconcile-run").click();
    await page.getByTestId("reconcile-report").waitFor({ state: "visible", timeout: 20_000 });
    const reconcileShot = resolve(screenshotsDir, "02-reconcile-report.png");
    await page.screenshot({ path: reconcileShot, fullPage: true });
    report.screenshots.push(artifactPath(reconcileShot));

    // --- Step 4: extract the app's own variance buckets as evidence.
    const appRows = await readReconcileReport(page);
    report.app_reconcile_rows = appRows;
    const totalDollarVariance =
      Math.round(rows.reduce((sum, r) => sum + (r.deltaUnits !== 0 ? Math.abs(r.deltaDollars) : 0), 0) * 100) / 100;
    const countedTotal = rows.reduce((sum, r) => sum + r.finalQty, 0);
    report.counted_total = countedTotal;
    report.total_dollar_variance = totalDollarVariance;
    report.variance_sku_count = rows.filter((r) => r.deltaUnits !== 0).length;
    report.per_sku = rows.map((row) => ({
      partNumber: row.partNumber,
      bookQty: row.bookQty,
      finalQty: row.finalQty,
      deltaUnits: row.deltaUnits,
      deltaDollars: row.deltaDollars,
      appBucket: findAppRow(appRows, row.partNumber)?.bucket ?? null,
    }));

    // --- Step 5: write the demo-ready markdown report.
    const markdown = await buildDemoMarkdown({
      mode: fixtures.mode,
      recordsTotal: report.records_total,
      countedTotal,
      totalDollarVariance,
      rows,
      appBuckets: appRows,
      runId,
      target: options.target,
      limitations,
    });
    await writeFile(resolve(runDir, "report.md"), markdown, "utf8");

    await context.close();
  } catch (error) {
    report.failures.push(error instanceof Error ? error.message : String(error));
  } finally {
    if (browser) await browser.close().catch(() => {});
    await writeFile(resolve(runDir, "report.json"), `${JSON.stringify(report, null, 2)}\n`, "utf8");
  }

  console.log(
    JSON.stringify({
      report_dir: artifactPath(runDir),
      data_source: report.data_source,
      records_total: report.records_total,
      counted_total: report.counted_total,
      total_dollar_variance: report.total_dollar_variance,
      limitations: report.limitations,
      failures: report.failures,
    }),
  );
  if (report.failures.length > 0) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack : String(error));
  process.exitCode = 1;
});
