import { randomUUID } from "node:crypto";
import type { IdentityLink, IdentityReview, IdentityTransformation, ImportOperation, ImportRun, ImportRunState } from "@/services/identity/types";
import type { AtomicLocalStorage, AtomicTransaction } from "./atomicLocalStorage";

const linksKey = "identity-links", transformationsKey = "identity-transformations", runsKey = "identity-runs", operationsKey = "identity-operations", reviewsKey = "identity-reviews";
type LinkLookup = Pick<IdentityLink, "businessId" | "sourceSystem" | "vendorId" | "sourceSignature" | "identifierType" | "namespace" | "normalizedValue">;
type OperationInput = Pick<ImportOperation, "businessId" | "importId" | "rowId" | "idempotencyKey" | "payloadFingerprint">;
export type ImportOperationClaim = { kind: "claimed"; operation: ImportOperation; leaseId: string } | { kind: "in_progress"; operation: ImportOperation } | { kind: "completed"; operation: ImportOperation; result: unknown } | { kind: "idempotency_conflict"; operation: ImportOperation } | { kind: "terminal"; operation: ImportOperation };
export interface LocalIdentityRepository {
  saveIdentityLink(link: IdentityLink): Promise<IdentityLink>; saveTransformation(rule: IdentityTransformation): Promise<IdentityTransformation>;
  resolveLink(input: LinkLookup): Promise<{ kind: "automatic"; link: IdentityLink } | { kind: "review"; link?: IdentityLink; transformation?: IdentityTransformation } | { kind: "abstain" }>;
  createImportRun(run: Omit<ImportRun, "state">): Promise<ImportRun>; getImportRun(businessId: string, importId: string): Promise<ImportRun | undefined>; transitionImportRun(businessId: string, importId: string, next: ImportRunState): Promise<ImportRun>;
  claimImportOperation(input: OperationInput, leaseMilliseconds: number): Promise<ImportOperationClaim>; completeImportOperation(operation: ImportOperation, leaseId: string, result: unknown): Promise<ImportOperation>; failImportOperation(operation: ImportOperation, leaseId: string, state: "failed_retryable" | "failed_terminal", result: unknown): Promise<ImportOperation>; saveIdentityReview(review: IdentityReview): Promise<IdentityReview>;
}
function required(...values: string[]): void { if (values.some((value) => !value.trim())) throw new Error("identity scope must be nonempty"); }
function scope(left: LinkLookup, right: LinkLookup): boolean { return left.businessId === right.businessId && left.sourceSystem === right.sourceSystem && left.vendorId === right.vendorId && left.sourceSignature === right.sourceSignature && left.identifierType === right.identifierType && left.namespace === right.namespace && left.normalizedValue === right.normalizedValue; }
function identityKey(input: Pick<ImportOperation, "businessId" | "importId" | "rowId">): string { return JSON.stringify([input.businessId, input.importId, input.rowId]); }
function latest<T extends { version: number }>(records: T[]): T | undefined { return records.reduce<T | undefined>((current, record) => !current || record.version > current.version ? record : current, undefined); }
const transitions: Record<ImportRunState, ImportRunState[]> = { previewed: ["applying", "invalidated"], applying: ["completed", "failed", "invalidated"], completed: [], failed: ["applying", "invalidated"], invalidated: [] };

export function createLocalRepository(storage: AtomicLocalStorage, { now = Date.now }: { now?: () => number } = {}): LocalIdentityRepository {
  async function requireOwnedLease(transaction: AtomicTransaction, operation: ImportOperation, leaseId: string): Promise<Record<string, ImportOperation>> { const operations = (await transaction.get<Record<string, ImportOperation>>(operationsKey)) ?? {}; const current = operations[identityKey(operation)]; if (!current || current.state !== "pending" || current.leaseId !== leaseId) throw new Error("Import operation lease is not owned"); if (!current.leaseExpiresAt || current.leaseExpiresAt <= now()) throw new Error("Import operation lease expired"); return operations; }
  return {
    async saveIdentityLink(link) { required(link.businessId, link.sourceSystem, link.vendorId, link.sourceSignature, link.namespace, link.normalizedValue, link.targetProductId); return storage.transaction(async (tx) => { const links = (await tx.get<IdentityLink[]>(linksKey)) ?? []; const family = links.filter((candidate) => scope(candidate, link)); const current = latest(family); if (current && link.version <= current.version) throw new Error("identity link version must increase"); if (link.status === "approved" && current?.status === "approved" && current.targetProductId !== link.targetProductId) throw new Error(`Approved identity link already belongs to ${current.targetProductId}`); links.push(link); await tx.set(linksKey, links); return link; }); },
    async saveTransformation(rule) { required(rule.businessId, rule.sourceSystem, rule.vendorId, rule.sourceSignature, rule.ruleKind); return storage.transaction(async (tx) => { const rules = (await tx.get<IdentityTransformation[]>(transformationsKey)) ?? []; const family = rules.filter((x) => x.businessId === rule.businessId && x.sourceSystem === rule.sourceSystem && x.vendorId === rule.vendorId && x.sourceSignature === rule.sourceSignature && x.ruleKind === rule.ruleKind); if ((latest(family)?.version ?? 0) >= rule.version) throw new Error("identity transformation version must increase"); rules.push(rule); await tx.set(transformationsKey, rules); return rule; }); },
    async resolveLink(input) { required(input.businessId, input.sourceSystem, input.vendorId, input.sourceSignature, input.namespace, input.normalizedValue); return storage.transaction(async (tx) => { const links = (await tx.get<IdentityLink[]>(linksKey)) ?? []; const exact = latest(links.filter((link) => scope(link, input))); if (exact?.status === "approved") return { kind: "automatic" as const, link: exact }; if (exact?.status === "proposed") return { kind: "review" as const, link: exact }; const rules = (await tx.get<IdentityTransformation[]>(transformationsKey)) ?? []; const rule = latest(rules.filter((x) => x.businessId === input.businessId && x.sourceSystem === input.sourceSystem && x.vendorId === input.vendorId && x.sourceSignature === "*")); return rule?.status === "approved" ? { kind: "review" as const, transformation: rule } : { kind: "abstain" as const }; }); },
    async createImportRun(run) { required(run.businessId, run.importId); return storage.transaction(async (tx) => { const runs = (await tx.get<ImportRun[]>(runsKey)) ?? []; const existing = runs.find((x) => x.businessId === run.businessId && x.importId === run.importId); if (existing) return existing; const created = { ...run, state: "previewed" as const }; runs.push(created); await tx.set(runsKey, runs); return created; }); },
    async getImportRun(businessId, importId) { return storage.transaction(async (tx) => ((await tx.get<ImportRun[]>(runsKey)) ?? []).find((x) => x.businessId === businessId && x.importId === importId)); },
    async transitionImportRun(businessId, importId, next) { return storage.transaction(async (tx) => { const runs = (await tx.get<ImportRun[]>(runsKey)) ?? []; const index = runs.findIndex((x) => x.businessId === businessId && x.importId === importId); if (index < 0) throw new Error(`Unknown import run ${importId}`); const current = runs[index]; if (!transitions[current.state].includes(next)) throw new Error(`Import run cannot transition from ${current.state} to ${next}`); const changed = { ...current, state: next }; runs[index] = changed; await tx.set(runsKey, runs); return changed; }); },
    async claimImportOperation(input, leaseMilliseconds) { required(input.businessId, input.importId, input.rowId, input.idempotencyKey, input.payloadFingerprint); if (!Number.isFinite(leaseMilliseconds) || leaseMilliseconds <= 0 || leaseMilliseconds > 300_000) throw new Error("lease must be finite, positive, and bounded"); return storage.transaction(async (tx) => { const runs = (await tx.get<ImportRun[]>(runsKey)) ?? []; if (!runs.some((run) => run.businessId === input.businessId && run.importId === input.importId && run.state === "applying")) throw new Error("matching import run is not applying"); const operations = (await tx.get<Record<string, ImportOperation>>(operationsKey)) ?? {}; const key = identityKey(input), existing = operations[key]; if (existing && (existing.idempotencyKey !== input.idempotencyKey || existing.payloadFingerprint !== input.payloadFingerprint)) return { kind: "idempotency_conflict" as const, operation: existing }; if (existing?.state === "applied") return { kind: "completed" as const, operation: existing, result: existing.result }; if (existing?.state === "failed_terminal") return { kind: "terminal" as const, operation: existing }; if (existing?.leaseExpiresAt && existing.leaseExpiresAt > now()) return { kind: "in_progress" as const, operation: existing }; const leaseId = randomUUID(), operation: ImportOperation = { ...input, state: "pending", leaseId, leaseExpiresAt: now() + leaseMilliseconds }; operations[key] = operation; await tx.set(operationsKey, operations); return { kind: "claimed" as const, operation, leaseId }; }); },
    async completeImportOperation(operation, leaseId, result) { return storage.transaction(async (tx) => { const operations = await requireOwnedLease(tx, operation, leaseId), key = identityKey(operation), completed = { ...operations[key], state: "applied" as const, leaseId: undefined, leaseExpiresAt: undefined, result }; operations[key] = completed; await tx.set(operationsKey, operations); return completed; }); },
    async failImportOperation(operation, leaseId, state, result) { return storage.transaction(async (tx) => { const operations = await requireOwnedLease(tx, operation, leaseId), key = identityKey(operation), failed = { ...operations[key], state, leaseId: undefined, leaseExpiresAt: undefined, result }; operations[key] = failed; await tx.set(operationsKey, operations); return failed; }); },
    async saveIdentityReview(review) { required(review.businessId, review.importId, review.rowId, review.reviewId); return storage.transaction(async (tx) => { const reviews = (await tx.get<IdentityReview[]>(reviewsKey)) ?? []; const index = reviews.findIndex((x) => x.businessId === review.businessId && x.reviewId === review.reviewId); if (index >= 0) reviews[index] = review; else reviews.push(review); await tx.set(reviewsKey, reviews); return review; }); },
  };
}
