import { createHash, randomUUID } from "node:crypto";
import { canonicalSha256, isValidIdentityNamespace } from "@/services/identity/canonical";
import type { ExpectedInventorySession, IdentityLink, IdentityReview, IdentityTransformation, ImportOperation, ImportRun, ImportRunState, ReviewAction, TenantIdentityProduct } from "@/services/identity/types";
import type { AtomicLocalStorage, AtomicPage, AtomicPageOptions, AtomicTransaction } from "./atomicLocalStorage";

const linksKey = "identity-links", transformationsKey = "identity-transformations", runsKey = "identity-runs", operationsKey = "identity-operations", reviewsKey = "identity-reviews", expectedSessionsKey = "expected-inventory-sessions", tenantProductsKey = "identity-tenant-products";
const emptyCurrentLinksFingerprint = createHash("sha256").update("[]").digest("hex");
export type LinkLookup = Pick<IdentityLink, "businessId" | "sourceSystem" | "vendorId" | "sourceSignature" | "identifierType" | "namespace" | "normalizedValue">;
export type IdentityLinkPageRecord = Pick<IdentityLink, "businessId" | "sourceSystem" | "vendorId" | "sourceSignature" | "identifierType" | "namespace" | "normalizedValue" | "targetProductId" | "status" | "version">;
export type AuthoritativeIdentityLinkPageItem = IdentityLinkPageRecord & { predecessorSource: "configured" | "durable" };
type OperationInput = Pick<ImportOperation, "businessId" | "importId" | "rowId" | "idempotencyKey" | "payloadFingerprint">;
export type ImportOperationClaim = { kind: "claimed"; operation: ImportOperation; leaseId: string } | { kind: "in_progress"; operation: ImportOperation } | { kind: "completed"; operation: ImportOperation; result: unknown } | { kind: "idempotency_conflict"; operation: ImportOperation } | { kind: "terminal"; operation: ImportOperation };
export interface LocalIdentityRepository {
  saveIdentityLink(link: IdentityLink): Promise<IdentityLink>; saveTransformation(rule: IdentityTransformation): Promise<IdentityTransformation>;
  resolveLink(input: LinkLookup): Promise<{ kind: "automatic"; link: IdentityLink } | { kind: "review"; link?: IdentityLink; transformation?: IdentityTransformation; transformations?: IdentityTransformation[] } | { kind: "abstain" }>;
  revokeIdentityLink(input: { link: IdentityLink; predecessor: { source: "configured" | "durable"; fingerprint: string; version: number } }): Promise<IdentityLink>; createImportRun(run: Omit<ImportRun, "state" | "result">): Promise<ImportRun>; getImportRun(businessId: string, importId: string): Promise<ImportRun | undefined>; transitionImportRun(businessId: string, importId: string, next: ImportRunState): Promise<ImportRun>; completeImportRun(businessId: string, importId: string, result: unknown): Promise<ImportRun>;
  saveExpectedInventorySession(session: ExpectedInventorySession): Promise<ExpectedInventorySession>; getExpectedInventorySession(businessId: string, importId: string): Promise<ExpectedInventorySession | undefined>;
  claimImportOperation(input: OperationInput, leaseMilliseconds: number): Promise<ImportOperationClaim>; completeImportOperation(operation: ImportOperation, leaseId: string, result: unknown): Promise<ImportOperation>; failImportOperation(operation: ImportOperation, leaseId: string, state: "failed_retryable" | "failed_terminal", result: unknown): Promise<ImportOperation>; saveIdentityReview(review: IdentityReview): Promise<IdentityReview>; getIdentityReview(businessId: string, reviewId: string): Promise<IdentityReview | undefined>; listIdentityReviews(businessId: string): Promise<IdentityReview[]>; pageIdentityReviews(businessId: string, input: { bucket?: string; page: number; pageSize: number }): Promise<{ items: IdentityReview[]; total: number; bucketTotals: Record<string, number> }>; listCurrentIdentityLinks(businessId: string): Promise<IdentityLink[]>; currentIdentityLinksFingerprint(businessId: string): Promise<string>; pageCurrentIdentityLinks(businessId: string, input: { page: number; pageSize: number }): Promise<{ items: IdentityLink[]; total: number }>; pageAuthoritativeIdentityLinks(businessId: string, input: { page: number; pageSize: number; configured: readonly IdentityLinkPageRecord[] }): Promise<{ items: AuthoritativeIdentityLinkPageItem[]; total: number }>; findCurrentIdentityLinks(businessId: string, lookups: readonly LinkLookup[]): Promise<IdentityLink[]>; listTenantProducts(businessId: string): Promise<TenantIdentityProduct[]>; resolveIdentityReview(businessId: string, reviewId: string, resolution: NonNullable<IdentityReview["resolution"]>, resolvedBy: string, resolvedAt: string): Promise<IdentityReview>; createTenantProduct(product: TenantIdentityProduct): Promise<TenantIdentityProduct>; applyReviewAction(input: { businessId: string; reviewId: string; actionId: string; payloadFingerprint: string; action: ReviewAction["action"]; resolution: NonNullable<IdentityReview["resolution"]>; resolvedBy: string; link?: IdentityLink; product?: TenantIdentityProduct }): Promise<{ review: IdentityReview; link?: IdentityLink; product?: TenantIdentityProduct; action: ReviewAction }>;
}
function required(...values: string[]): void { if (values.some((value) => !value.trim())) throw new Error("identity scope must be nonempty"); }
function requiredLinkScope(link: Pick<IdentityLink, "businessId" | "sourceSystem" | "vendorId" | "sourceSignature" | "identifierType" | "namespace" | "normalizedValue" | "targetProductId">): void { required(link.businessId, link.sourceSystem, link.vendorId, link.sourceSignature, link.normalizedValue, link.targetProductId); if (!isValidIdentityNamespace(link.identifierType, link.namespace)) throw new Error("identity link namespace is invalid"); }
function scope(left: LinkLookup, right: LinkLookup): boolean { return left.businessId === right.businessId && left.sourceSystem === right.sourceSystem && left.vendorId === right.vendorId && left.sourceSignature === right.sourceSignature && left.identifierType === right.identifierType && left.namespace === right.namespace && left.normalizedValue === right.normalizedValue; }
function linkFamilyKey(link: IdentityLinkPageRecord): string { return JSON.stringify([link.businessId, link.sourceSystem, link.vendorId, link.sourceSignature, link.identifierType, link.namespace, link.normalizedValue]); }
function compareLinks(left: IdentityLinkPageRecord, right: IdentityLinkPageRecord): number { return left.normalizedValue.localeCompare(right.normalizedValue) || linkFamilyKey(left).localeCompare(linkFamilyKey(right)) || left.version - right.version; }
function pageBounds(input: { page: number; pageSize: number }): { offset: number; limit: number } { const page = Number.isSafeInteger(input.page) && input.page > 0 ? input.page : 1, limit = Number.isSafeInteger(input.pageSize) && input.pageSize > 0 ? Math.min(input.pageSize, 25) : 25; return { offset: (page - 1) * limit, limit }; }
function scanPage<T>(transaction: AtomicTransaction, key: string, options: AtomicPageOptions<T>): Promise<AtomicPage<T>> { if (!transaction.scanPage) throw new Error("bounded identity storage reads are unavailable"); return transaction.scanPage(key, options); }
function identityKey(input: Pick<ImportOperation, "businessId" | "importId" | "rowId">): string { return JSON.stringify([input.businessId, input.importId, input.rowId]); }
function latest<T extends { version: number }>(records: T[]): T | undefined { return records.reduce<T | undefined>((current, record) => !current || record.version > current.version ? record : current, undefined); }
function predecessorFields(link: Pick<IdentityLink, "businessId" | "sourceSystem" | "sourceSignature" | "vendorId" | "identifierType" | "namespace" | "normalizedValue" | "targetProductId" | "version">): unknown { return { businessId: link.businessId, sourceSystem: link.sourceSystem, sourceSignature: link.sourceSignature, vendorId: link.vendorId, identifierType: link.identifierType, namespace: link.namespace, normalizedValue: link.normalizedValue, targetProductId: link.targetProductId, version: link.version }; }
function immutableRun(run: ImportRun | Omit<ImportRun, "state">): Omit<Omit<ImportRun, "state">, "createdAt"> { return { importId: run.importId, businessId: run.businessId, sourceFingerprint: run.sourceFingerprint, mappingFingerprint: run.mappingFingerprint, previewFingerprint: run.previewFingerprint, actorId: run.actorId, engineVersion: run.engineVersion, pluginVersion: run.pluginVersion, catalogVersion: run.catalogVersion, ...(run.operationFingerprint ? { operationFingerprint: run.operationFingerprint } : {}) }; }
function immutableReview(review: IdentityReview): Record<string, unknown> { return { reviewId: review.reviewId, businessId: review.businessId, importId: review.importId, rowId: review.rowId, decision: review.decision, ...(review.scope ? { scope: review.scope } : {}), ...(review.signedRowContext ? { signedRowContext: review.signedRowContext } : {}) }; }
function latestTransformations(rules: IdentityTransformation[], input: Pick<IdentityTransformation, "businessId" | "sourceSystem" | "vendorId">): IdentityTransformation[] {
  const families = new Map<string, IdentityTransformation[]>();
  for (const rule of rules) {
    if (rule.businessId !== input.businessId || rule.sourceSystem !== input.sourceSystem || rule.vendorId !== input.vendorId || rule.sourceSignature !== "*") continue;
    const family = `${rule.sourceSignature}\u0000${rule.ruleKind}`;
    families.set(family, [...(families.get(family) ?? []), rule]);
  }
  return [...families.values()].map((family) => latest(family)).filter((rule): rule is IdentityTransformation => Boolean(rule && (rule.status === "approved" || rule.status === "proposed"))).sort((left, right) => left.ruleKind.localeCompare(right.ruleKind) || left.version - right.version);
}
const transitions: Record<ImportRunState, ImportRunState[]> = { previewed: ["applying", "invalidated"], applying: ["completed", "failed", "invalidated"], completed: [], failed: ["applying", "invalidated"], invalidated: [] };

export function createLocalRepository(storage: AtomicLocalStorage, { now = Date.now }: { now?: () => number } = {}): LocalIdentityRepository {
  const read = storage.read ? storage.read.bind(storage) : storage.transaction.bind(storage);
  async function requireOwnedLease(transaction: AtomicTransaction, operation: ImportOperation, leaseId: string): Promise<Record<string, ImportOperation>> { const runs = (await transaction.get<ImportRun[]>(runsKey)) ?? []; if (!runs.some((run) => run.businessId === operation.businessId && run.importId === operation.importId && run.state === "applying")) throw new Error("matching import run is not applying"); const operations = (await transaction.get<Record<string, ImportOperation>>(operationsKey)) ?? {}; const current = operations[identityKey(operation)]; if (!current || current.state !== "pending" || current.leaseId !== leaseId) throw new Error("Import operation lease is not owned"); if (!current.leaseExpiresAt || current.leaseExpiresAt <= now()) throw new Error("Import operation lease expired"); return operations; }
  return {
    async saveIdentityLink(link) { requiredLinkScope(link); return storage.transaction(async (tx) => { const links = (await tx.get<IdentityLink[]>(linksKey)) ?? []; const family = links.filter((candidate) => scope(candidate, link)); const current = latest(family); if (current && link.version <= current.version) throw new Error("identity link version must increase"); if (link.status === "approved" && current?.status === "approved" && current.targetProductId !== link.targetProductId) throw new Error(`Approved identity link already belongs to ${current.targetProductId}`); links.push(link); await tx.set(linksKey, links); return link; }); },
    async revokeIdentityLink(input) { requiredLinkScope(input.link); required(input.predecessor.fingerprint); return storage.transaction(async (tx) => { const links = (await tx.get<IdentityLink[]>(linksKey)) ?? []; const family = links.filter((candidate) => scope(candidate, input.link)); const current = latest(family); if (input.predecessor.source === "configured") { if (current) throw new Error("identity_link_revoke_conflict"); } else { if (!current || current.status !== "approved" || current.version !== input.predecessor.version || current.targetProductId !== input.link.targetProductId || await canonicalSha256(predecessorFields(current)) !== input.predecessor.fingerprint) throw new Error("identity_link_revoke_conflict"); } const revoked: IdentityLink = { ...input.link, status: "revoked", version: Math.max(current?.version ?? 0, input.predecessor.version) + 1 }; links.push(revoked); await tx.set(linksKey, links); return revoked; }); },
    async saveTransformation(rule) { required(rule.businessId, rule.sourceSystem, rule.vendorId, rule.sourceSignature, rule.ruleKind); return storage.transaction(async (tx) => { const rules = (await tx.get<IdentityTransformation[]>(transformationsKey)) ?? []; const family = rules.filter((x) => x.businessId === rule.businessId && x.sourceSystem === rule.sourceSystem && x.vendorId === rule.vendorId && x.sourceSignature === rule.sourceSignature && x.ruleKind === rule.ruleKind); if ((latest(family)?.version ?? 0) >= rule.version) throw new Error("identity transformation version must increase"); rules.push(rule); await tx.set(transformationsKey, rules); return rule; }); },
    async resolveLink(input) { requiredLinkScope({ ...input, targetProductId: "lookup" }); return read(async (tx) => { const links = (await tx.get<IdentityLink[]>(linksKey)) ?? []; const exact = latest(links.filter((link) => scope(link, input))); if (exact?.status === "approved") return { kind: "automatic" as const, link: exact }; if (exact?.status === "proposed") return { kind: "review" as const, link: exact }; const rules = latestTransformations((await tx.get<IdentityTransformation[]>(transformationsKey)) ?? [], input); if (!rules.length) return { kind: "abstain" as const }; return { kind: "review" as const, transformation: rules.length === 1 ? rules[0] : undefined, transformations: rules }; }); },
    async createImportRun(run) { required(run.businessId, run.importId); return storage.transaction(async (tx) => { const runs = (await tx.get<ImportRun[]>(runsKey)) ?? []; const existing = runs.find((x) => x.businessId === run.businessId && x.importId === run.importId); if (existing) { const [previous, incoming] = await Promise.all([canonicalSha256(immutableRun(existing)), canonicalSha256(immutableRun(run))]); if (previous !== incoming) throw new Error("import run idempotency conflict"); return existing; } const created = { ...run, state: "previewed" as const }; runs.push(created); await tx.set(runsKey, runs); return created; }); },
    async getImportRun(businessId, importId) { return read(async (tx) => ((await tx.get<ImportRun[]>(runsKey)) ?? []).find((x) => x.businessId === businessId && x.importId === importId)); },
    async transitionImportRun(businessId, importId, next) { return storage.transaction(async (tx) => { const runs = (await tx.get<ImportRun[]>(runsKey)) ?? []; const index = runs.findIndex((x) => x.businessId === businessId && x.importId === importId); if (index < 0) throw new Error(`Unknown import run ${importId}`); const current = runs[index]; if (current.state === next) return current; if (!transitions[current.state].includes(next)) throw new Error(`Import run cannot transition from ${current.state} to ${next}`); const changed = { ...current, state: next }; runs[index] = changed; await tx.set(runsKey, runs); return changed; }); },
    async completeImportRun(businessId, importId, result) { return storage.transaction(async (tx) => { const runs = (await tx.get<ImportRun[]>(runsKey)) ?? []; const index = runs.findIndex((x) => x.businessId === businessId && x.importId === importId); if (index < 0) throw new Error(`Unknown import run ${importId}`); const current = runs[index]; if (current.state === "completed") return current; if (current.state !== "applying") throw new Error("matching import run is not applying"); const completed = { ...current, state: "completed" as const, result }; runs[index] = completed; await tx.set(runsKey, runs); return completed; }); },
    async saveExpectedInventorySession(session) { return storage.transaction(async (tx) => { const sessions = (await tx.get<ExpectedInventorySession[]>(expectedSessionsKey)) ?? []; const existing = sessions.find((item) => item.businessId === session.businessId && item.importId === session.importId); if (existing) return existing; sessions.push(session); await tx.set(expectedSessionsKey, sessions); return session; }); },
    async getExpectedInventorySession(businessId, importId) { return read(async (tx) => ((await tx.get<ExpectedInventorySession[]>(expectedSessionsKey)) ?? []).find((item) => item.businessId === businessId && item.importId === importId)); },
    async claimImportOperation(input, leaseMilliseconds) { required(input.businessId, input.importId, input.rowId, input.idempotencyKey, input.payloadFingerprint); if (!Number.isFinite(leaseMilliseconds) || leaseMilliseconds <= 0 || leaseMilliseconds > 300_000) throw new Error("lease must be finite, positive, and bounded"); return storage.transaction(async (tx) => { const runs = (await tx.get<ImportRun[]>(runsKey)) ?? []; if (!runs.some((run) => run.businessId === input.businessId && run.importId === input.importId && run.state === "applying")) throw new Error("matching import run is not applying"); const operations = (await tx.get<Record<string, ImportOperation>>(operationsKey)) ?? {}; const key = identityKey(input), existing = operations[key]; if (existing && (existing.idempotencyKey !== input.idempotencyKey || existing.payloadFingerprint !== input.payloadFingerprint)) return { kind: "idempotency_conflict" as const, operation: existing }; if (existing?.state === "applied") return { kind: "completed" as const, operation: existing, result: existing.result }; if (existing?.state === "failed_terminal") return { kind: "terminal" as const, operation: existing }; if (existing?.leaseExpiresAt && existing.leaseExpiresAt > now()) return { kind: "in_progress" as const, operation: existing }; const leaseId = randomUUID(), operation: ImportOperation = { ...input, state: "pending", leaseId, leaseExpiresAt: now() + leaseMilliseconds }; operations[key] = operation; await tx.set(operationsKey, operations); return { kind: "claimed" as const, operation, leaseId }; }); },
    async completeImportOperation(operation, leaseId, result) { return storage.transaction(async (tx) => { const operations = await requireOwnedLease(tx, operation, leaseId), key = identityKey(operation), completed = { ...operations[key], state: "applied" as const, leaseId: undefined, leaseExpiresAt: undefined, result }; operations[key] = completed; await tx.set(operationsKey, operations); return completed; }); },
    async failImportOperation(operation, leaseId, state, result) { return storage.transaction(async (tx) => { const operations = await requireOwnedLease(tx, operation, leaseId), key = identityKey(operation), failed = { ...operations[key], state, leaseId: undefined, leaseExpiresAt: undefined, result }; operations[key] = failed; await tx.set(operationsKey, operations); return failed; }); },
    async saveIdentityReview(review) { required(review.businessId, review.importId, review.rowId, review.reviewId); if (review.resolution || review.resolvedBy || review.resolvedAt) throw new Error("identity review must be created unresolved"); return storage.transaction(async (tx) => { const reviews = (await tx.get<IdentityReview[]>(reviewsKey)) ?? []; const existing = reviews.find((x) => x.businessId === review.businessId && x.reviewId === review.reviewId); if (existing) { const [previous, incoming] = await Promise.all([canonicalSha256(immutableReview(existing)), canonicalSha256(immutableReview(review))]); if (previous !== incoming) throw new Error("identity review idempotency conflict"); return existing; } reviews.push(review); await tx.set(reviewsKey, reviews); return review; }); },
    async getIdentityReview(businessId, reviewId) { required(businessId, reviewId); return read(async (tx) => ((await tx.get<IdentityReview[]>(reviewsKey)) ?? []).find((review) => review.businessId === businessId && review.reviewId === reviewId)); },
    async listIdentityReviews(businessId) { required(businessId); return read(async (tx) => ((await tx.get<IdentityReview[]>(reviewsKey)) ?? []).filter((review) => review.businessId === businessId && !review.resolution).sort((left, right) => left.reviewId.localeCompare(right.reviewId))); },
    async pageIdentityReviews(businessId, input) { required(businessId); const bounds = pageBounds(input); return read(async (tx) => { const result = await scanPage<IdentityReview>(tx, reviewsKey, { ...bounds, filter: (review) => review.businessId === businessId && !review.resolution, visible: input.bucket ? (review) => review.decision.kind === input.bucket : undefined, compare: (left, right) => left.reviewId.localeCompare(right.reviewId), groupBy: (review) => review.decision.kind, physical: { kind: "identity-reviews", businessId, ...(input.bucket ? { bucket: input.bucket } : {}) } }); return { items: result.items, total: result.total, bucketTotals: Object.fromEntries(["automatic", "review", "abstain", "non_product", "invalid"].map((kind) => [kind, result.groupTotals[kind] ?? 0])) }; }); },
    async listCurrentIdentityLinks(businessId) { required(businessId); return read(async (tx) => { const byFamily = new Map<string, IdentityLink>(); for (const link of (await tx.get<IdentityLink[]>(linksKey)) ?? []) { if (link.businessId !== businessId) continue; const key = JSON.stringify([link.businessId, link.sourceSystem, link.vendorId, link.sourceSignature, link.identifierType, link.namespace, link.normalizedValue]); const current = byFamily.get(key); if (!current || link.version > current.version) byFamily.set(key, link); } return [...byFamily.values()].sort((a, b) => a.normalizedValue.localeCompare(b.normalizedValue) || a.version - b.version); }); },
    async currentIdentityLinksFingerprint(businessId) { required(businessId); return read(async (tx) => { const result = await scanPage<IdentityLink>(tx, linksKey, { offset: 0, limit: 1, filter: (link) => link.businessId === businessId, compare: compareLinks, collapseBy: linkFamilyKey, versionOf: (link) => link.version, physical: { kind: "identity-links", businessId, mode: "current" } }); return result.fingerprint ?? emptyCurrentLinksFingerprint; }); },
    async pageCurrentIdentityLinks(businessId, input) { required(businessId); const bounds = pageBounds(input); return read(async (tx) => { const result = await scanPage<IdentityLink>(tx, linksKey, { ...bounds, filter: (link) => link.businessId === businessId, compare: compareLinks, collapseBy: linkFamilyKey, versionOf: (link) => link.version, physical: { kind: "identity-links", businessId, mode: "current" } }); return { items: result.items, total: result.total }; }); },
    async pageAuthoritativeIdentityLinks(businessId, input) { required(businessId); const bounds = pageBounds(input); return read(async (tx) => { type PageRecord = IdentityLink | IdentityLinkPageRecord; const result = await scanPage<PageRecord>(tx, linksKey, { ...bounds, baseItems: input.configured, filter: (link) => link.businessId === businessId, visible: (link) => link.status === "approved", compare: compareLinks, collapseBy: linkFamilyKey, versionOf: (link) => link.version, physical: { kind: "identity-links", businessId, mode: "authoritative" } }); return { items: result.items.map((link, index) => ({ businessId: link.businessId, sourceSystem: link.sourceSystem, vendorId: link.vendorId, sourceSignature: link.sourceSignature, identifierType: link.identifierType, namespace: link.namespace, normalizedValue: link.normalizedValue, targetProductId: link.targetProductId, status: link.status, version: link.version, predecessorSource: result.origins[index] === "stored" ? "durable" as const : "configured" as const })), total: result.total }; }); },
    async findCurrentIdentityLinks(businessId, lookups) { required(businessId); if (!lookups.length) return []; const requested = new Set(lookups.slice(0, 25).map((lookup) => linkFamilyKey(lookup as IdentityLinkPageRecord))); return read(async (tx) => (await scanPage<IdentityLink>(tx, linksKey, { offset: 0, limit: Math.max(1, requested.size), filter: (link) => link.businessId === businessId, visible: (link) => requested.has(linkFamilyKey(link)), compare: compareLinks, collapseBy: linkFamilyKey, versionOf: (link) => link.version, physical: { kind: "identity-links", businessId, mode: "families", families: [...requested] } })).items); },
    async listTenantProducts(businessId) { required(businessId); return read(async (tx) => ((await tx.get<TenantIdentityProduct[]>(tenantProductsKey)) ?? []).filter((product) => product.businessId === businessId).sort((a, b) => a.productId.localeCompare(b.productId))); },
    async resolveIdentityReview(businessId, reviewId, resolution, resolvedBy, clientResolvedAt) { required(businessId, reviewId, resolution, resolvedBy, clientResolvedAt); void clientResolvedAt; return storage.transaction(async (tx) => { const reviews = (await tx.get<IdentityReview[]>(reviewsKey)) ?? []; const index = reviews.findIndex((review) => review.businessId === businessId && review.reviewId === reviewId); if (index < 0) throw new Error(`Unknown identity review ${reviewId}`); const current = reviews[index]; if (current.resolution) { if (current.resolution === resolution && current.resolvedBy === resolvedBy) return current; throw new Error("identity review is terminal and cannot be rewritten"); } const resolved = { ...current, resolution, resolvedBy, resolvedAt: new Date(now()).toISOString() }; reviews[index] = resolved; await tx.set(reviewsKey, reviews); return resolved; }); },
    async createTenantProduct(product) { required(product.productId, product.businessId, product.name, product.createdBy, product.createdAt); return storage.transaction(async (tx) => { const products = (await tx.get<TenantIdentityProduct[]>(tenantProductsKey)) ?? []; if (products.some((item) => item.businessId === product.businessId && item.productId === product.productId)) throw new Error("tenant product already exists"); products.push(product); await tx.set(tenantProductsKey, products); return product; }); },
    async applyReviewAction(input) { required(input.businessId, input.reviewId, input.actionId, input.payloadFingerprint, input.resolvedBy); return storage.transaction(async (tx) => { const reviews = (await tx.get<IdentityReview[]>(reviewsKey)) ?? []; const i = reviews.findIndex((x) => x.businessId === input.businessId && x.reviewId === input.reviewId); if (i < 0) throw new Error(`Unknown identity review ${input.reviewId}`); const current = reviews[i]!; if (current.reviewAction) { if (current.reviewAction.actionId !== input.actionId || current.reviewAction.payloadFingerprint !== input.payloadFingerprint) throw new Error("identity_review_action_conflict"); return { review: current, ...(current.reviewAction.link ? { link: current.reviewAction.link } : {}), action: current.reviewAction }; } if (current.resolution) throw new Error("identity_review_terminal"); let product = input.product; if (product) { const products = (await tx.get<TenantIdentityProduct[]>(tenantProductsKey)) ?? []; const found = products.find((x) => x.businessId === product!.businessId && x.productId === product!.productId); if (!found) { products.push(product); await tx.set(tenantProductsKey, products); } else product = found; } let link: IdentityLink | undefined, previousTargetProductId: string | undefined; if (input.link) { const links = (await tx.get<IdentityLink[]>(linksKey)) ?? []; const family = links.filter((x) => scope(x, input.link!)); const old = latest(family); previousTargetProductId = old?.status === "approved" ? old.targetProductId : undefined; if ((input.action === "revoke_link" && (!old || old.status !== "approved" || old.targetProductId !== input.link.targetProductId)) || (input.action !== "revoke_link" && old?.status === "approved" && old.targetProductId !== input.link.targetProductId)) throw new Error(input.action === "revoke_link" ? "identity_review_revoke_conflict" : "identity_review_target_conflict"); link = { ...input.link, version: (old?.version ?? 0) + 1, status: input.action === "revoke_link" ? "revoked" : "approved" }; links.push(link); await tx.set(linksKey, links); } const resolvedAt = new Date(now()).toISOString(); const outcome: ReviewAction["outcome"] = input.action === "confirm_candidate" ? "confirmed" : input.action === "create_tenant_product" ? "create_product" : input.action === "revoke_link" ? "revoked" : "rejected"; const action: ReviewAction = { actionId: input.actionId, payloadFingerprint: input.payloadFingerprint, action: input.action, ...(link ? { targetProductId: link.targetProductId, link } : {}), ...(previousTargetProductId ? { previousTargetProductId } : {}), ...(product ? { productId: product.productId } : {}), outcome, resolvedBy: input.resolvedBy, resolvedAt }; const review = { ...current, resolution: input.resolution, resolvedBy: input.resolvedBy, resolvedAt, reviewAction: action }; reviews[i] = review; await tx.set(reviewsKey, reviews); return { review, ...(link ? { link } : {}), ...(product ? { product } : {}), action }; }); },
  };
}
